// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/weridolin/alinLab-webhook/webhook/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/webhook/api/v1/:uuid",
				Handler: WebhookCalledHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/webhook/api/v1/:uuid",
				Handler: WebhookCalledHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/webhook/api/v1/:uuid/history",
				Handler: historyHandler(serverCtx),
			},
		},
	)
}
